### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined in ~/git/saas-dr/.remote-sync.json

### ISSUE THREAD

**Issue by JianboZheng** [yongkangchen/remote-sync#412] opened 2017-06-07 18:36 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in /Users/jianbozheng/git/saas-dr/.remote-sync.json

```
At /Users/jianbozheng/.atom/packages/remote-sync/lib/RemoteSync.coffee:256

Error: [remote-sync] invalid transport: undefined in /Users/jianbozheng/git/saas-dr/.remote-sync.json
    at RemoteSync.createTransport (/packages/remote-sync/lib/RemoteSync.coffee:256:17)
    at RemoteSync.getTransport (/packages/remote-sync/lib/RemoteSync.coffee:262:19)
    at RemoteSync.uploadFile (/packages/remote-sync/lib/RemoteSync.coffee:108:37)
    at handleEvent (/packages/remote-sync/index.coffee:46:14)
    at /packages/remote-sync/index.coffee:100:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1306:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:09.1.0 application:reopen-project (input.hidden-input)
     -0:02.9.0 remote-sync:upload-file (span.syntax--comment.syntax--line.syntax--number-sign.syntax--python)
```

### Non-Core Packages

```
atom-clock 0.1.8 
git-plus 7.9.3 
git-projects 1.17.0 
remote-sync 4.1.5 
```

**Comment by AdsonCicilioti** [comment] 2017-08-02 22:23
Same problem.. Abandoned project.

**Comment by daverickdunn** [comment] 2017-10-26 14:07
Duplicate of #285

**Closed by daverickdunn** 2017-10-26 14:07 UTC
