### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/dev/redperevozki./*'

### ISSUE THREAD

**Issue by alexeylozenko** [yongkangchen/remote-sync#432] opened 2017-08-06 18:56 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/home/arc/dev/redperevozki./*'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/home/arc/dev/redperevozki./*'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at RemoteSync.isDirectory (/packages/remote-sync/lib/RemoteSync.coffee:200:23)
    at RemoteSync.monitorFile (/packages/remote-sync/lib/RemoteSync.coffee:134:42)
    at /packages/remote-sync/lib/RemoteSync.coffee:225:13
```

### Commands

```
  2x -5:30.7.0 editor:select-to-end-of-word (input.hidden-input)
  3x -5:29.9.0 core:select-left (input.hidden-input)
  2x -5:27.8.0 core:backspace (input.hidden-input)
     -5:27.6.0 intentions:highlight (input.hidden-input)
     -5:27.5.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -5:27.1.0 core:backspace (input.hidden-input)
     -5:26.8.0 editor:newline (input.hidden-input)
     -5:23.7.0 intentions:highlight (input.hidden-input)
     -5:23.5.0 core:save (input.hidden-input)
     -5:20.5.0 core:backspace (input.hidden-input)
     -5:20.1.0 intentions:highlight (input.hidden-input)
     -5:20 core:save (input.hidden-input)
     -4:57.4.0 intentions:highlight (input.hidden-input)
     -4:57.3.0 core:save (input.hidden-input)
     -2:12.7.0 tree-view:toggle (div.panels-item)
  7x -0:27 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
css-snippets 1.1.0 
emmet 2.4.3 
intentions 1.1.5 
javascript-snippets 1.2.1 
node-debugger 1.10.1 
platformio-ide-terminal 2.5.4 
remote-sync 4.1.5 
```

**Comment by daverickdunn** [comment] 2017-11-05 16:17
Duplicate of issue: #273

**Closed by daverickdunn** 2017-11-05 16:17 UTC
