### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Kvilios** [yongkangchen/remote-sync#444] opened 2017-10-05 18:55 UTC
![image](https://user-images.githubusercontent.com/30824788/31246981-d65a2d10-aa17-11e7-9fed-de45be68671f.png)
Where is the "Remote Sync > Configure"?

**Comment by daverickdunn** [comment] 2017-10-13 12:53
Duplicate of https://github.com/yongkangchen/remote-sync/issues/440

Will patch in the coming days.

**Closed by daverickdunn** 2017-10-13 12:53 UTC
