### ISSUE TITLE
Uncaught TypeError: q.drain is not a function

### ISSUE THREAD

**Issue by raj82q** [yongkangchen/remote-sync#374] opened 2017-03-05 08:23 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At C:\Users\vibhor\.atom\packages\remote-sync\node_modules\fs-plus\node_modules\async\lib\async.js:909

TypeError: q.drain is not a function
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909:23
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:44:16
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -1:01.3.0 remote-sync:diff-folder (span.name.icon.icon-file-directory)
     -0:43.1.0 remote-sync:download-folder (span.name.icon.icon-file-directory)
  2x -0:38.7.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
remote-edit 1.9.0  - Disabled
Remote-FTP 0.10.7 - Disabled
remote-sync 4.1.5 
split-diff 1.2.0 
```

**Comment by DiegoYungh** [comment] 2017-03-16 10:44
[Enter steps to reproduce:]

1. Fresh new project
2. Right click on main folder -> Remote Sync -> Upload Folder

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5


### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At C:\Users\yungh\.atom\packages\remote-sync\node_modules\fs-plus\node_modules\async\lib\async.js:909

TypeError: q.drain is not a function
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909:23
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:44:16
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:48.5.0 remote-sync:upload-folder (div.header.list-item.project-root-header)
     -0:39.9.0 remote-sync:configure (div.header.list-item.project-root-header)
     -0:14.8.0 remote-sync:upload-folder (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
intentions 1.1.2 
linter 2.1.0 
linter-js-standard 3.9.0 
linter-tidy 2.3.0 
linter-ui-default 1.1.0 
php-twig 4.0.0 
remote-sync 4.1.5 
text-manipulation 0.6.0 
```

**Comment by Pasha49** [comment] 2017-03-23 14:17
[Enter steps to reproduce:]

1. Right click on main folder -> Remote Sync -> Upload Folder


**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5


### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At /home/pasha/.atom/packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909

TypeError: q.drain is not a function
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909:23
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:44:16
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
  2x -2:22.5.0 tree-view:remove (span.name.icon.python-icon.dark-blue)
  3x -2:10.2.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-django 0.3.2 
autocomplete-php 0.3.7 
autocomplete-python 1.8.62 
busy-signal 1.3.0 
django-templates 0.5.0 
emmet 2.4.3 
file-icons 2.1.1 
highlight-selected 0.12.0 
intentions 1.1.2 
linter 2.1.2 
linter-php 1.3.2 
linter-pylama 0.8.16 
linter-ui-default 1.2.1 
minimap 4.26.8 
php-debug 0.2.4 
project-viewer 1.0.12 
python-debugger 0.2.0 
python-tools 0.6.9 
python-yapf 0.13.0 
remote-edit 1.9.0 
Remote-FTP 0.10.7 
remote-sync 4.1.5 
script 3.14.1 
seti-icons 1.4.3 
seti-ui 1.7.0 
sync-settings 0.8.1 
```

**Comment by ph55** [comment] 2017-03-24 21:53
[Enter steps to reproduce:]

1. Right click on main folder -> Remote Sync -> Upload Folder

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5


### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At C:\Users\alex\.atom\packages\remote-sync\node_modules\fs-plus\node_modules\async\lib\async.js:909

TypeError: q.drain is not a function
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909:23
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:44:16
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -2:19.4.0 core:save (input.hidden-input)
     -2:12.2.0 core:backspace (input.hidden-input)
     -2:12.1.0 intentions:highlight (input.hidden-input)
  2x -2:11.9.0 core:save (input.hidden-input)
     -1:53 intentions:highlight (input.hidden-input)
     -1:52.8.0 command-palette:toggle (input.hidden-input)
  8x -1:50.1.0 core:move-down (input.hidden-input)
  2x -1:45.6.0 core:move-up (input.hidden-input)
  3x -1:44.6.0 core:move-down (input.hidden-input)
     -1:43.8.0 core:move-up (input.hidden-input)
     -1:39.8.0 editor:consolidate-selections (input.hidden-input)
     -1:39.8.0 core:cancel (input.hidden-input)
     -1:23.3.0 editor:newline (input.hidden-input)
     -1:23.1.0 intentions:highlight (input.hidden-input)
     -1:22.9.0 core:save (input.hidden-input)
     -0:14.9.0 remote-sync:upload-folder (span.name.icon.icon-repo)
```

### Non-Core Packages

```
busy-signal 1.3.0 
editorconfig 2.2.2 
git-plus 7.3.3 
intentions 1.1.2 
language-lua 0.9.11 
language-moonscript 1.7.1 
language-nginx 0.6.2 
linter 2.1.2 
linter-lua 1.0.4 
linter-moonscript 1.1.1 
linter-ui-default 1.2.1 
remote-sync 4.1.5 
sync-settings 0.8.1 
```

**Comment by adamspruijt** [comment] 2017-03-31 19:52
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5


### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At C:\Users\aspruijt\.atom\packages\remote-sync\node_modules\fs-plus\node_modules\async\lib\async.js:909

TypeError: q.drain is not a function
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909:23
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:44:16
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
  2x -7:47.3.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
     -6:19 remote-sync:upload-file (span.name.icon.php-icon.dark-blue)
     -2:37 editor:consolidate-selections (input.hidden-input)
     -2:37 core:cancel (input.hidden-input)
     -1:52.6.0 intentions:highlight (input.hidden-input)
     -1:52.4.0 command-palette:toggle (input.hidden-input)
     -1:44.7.0 core:confirm (input.hidden-input)
     -1:44.7.0 settings-view:open (input.hidden-input)
  3x -1:08.2.0 core:backspace (input.hidden-input)
     -1:07.0 core:save (input.hidden-input)
     -1:04.1.0 core:undo (input.hidden-input)
  8x -0:54.1.0 core:backspace (input.hidden-input)
     -0:49.4.0 core:undo (input.hidden-input)
  8x -0:31.9.0 core:backspace (input.hidden-input)
     -0:30.1.0 core:save (input.hidden-input)
     -0:25.8.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
busy-signal 1.3.0 
color-picker 2.2.5 
docblockr 0.9.4 
emmet 2.4.3 
file-icons 2.1.2 
git-plus 7.3.3 
intentions 1.1.2 
language-mjml 1.9.0 
linter 2.1.2 
linter-php 1.3.2 
linter-ui-default 1.2.2 
mjml-preview 1.3.0 
php-debug 0.2.4 
project-manager 3.3.4 
remote-sync 4.1.5 
todo-show 1.11.0 
tree-view-git-status 1.3.1 
```

**Comment by cyril851122** [comment] 2017-04-14 04:37
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5


### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At C:\Users\jiangz3\.atom\packages\remote-sync\node_modules\fs-plus\node_modules\async\lib\async.js:909

TypeError: q.drain is not a function
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909:23
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:44:16
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -2:30.6.0 core:copy (input.hidden-input)
     -2:29.3.0 find-and-replace:show (input.hidden-input)
     -2:29.1.0 core:paste (input.hidden-input)
     -2:04.1.0 editor:consolidate-selections (input.hidden-input)
     -2:04.1.0 core:cancel (input.hidden-input)
     -1:51.2.0 core:copy (input.hidden-input)
     -1:50.5.0 find-and-replace:show (input.hidden-input)
     -1:50.3.0 core:paste (input.hidden-input)
 29x -1:49.6.0 core:confirm (input.hidden-input)
     -1:23.7.0 editor:consolidate-selections (input.hidden-input)
     -1:23.7.0 core:cancel (input.hidden-input)
     -1:13 find-and-replace:show (input.hidden-input)
  3x -1:12.7.0 core:confirm (input.hidden-input)
     -1:10.8.0 editor:consolidate-selections (input.hidden-input)
     -1:10.8.0 core:cancel (input.hidden-input)
     -1:01.2.0 remote-sync:upload-folder (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
atom-python-run 0.7.3 
autocomplete-python 1.8.63 
duotone-light-syntax 2.1.0 
remote-sync 4.1.5 
```

**Comment by riteshnanda09** [comment] 2017-04-18 22:33
Do we have any solution to it

**Comment by Psype** [comment] 2017-05-16 15:08
I tried to update node deps, nothing. The error is still here. But it uploads!

I don't know what to do to fixt it, and can't take time to look up about it yet =/

**Comment by yugihuang** [comment] 2017-05-18 02:17
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5


### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At /Users/eltech/.atom/packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909

TypeError: q.drain is not a function
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909:23
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:44:16
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -8:20.3.0 core:paste (input.hidden-input)
  2x -8:18.9.0 core:save (input.hidden-input)
     -8:10.1.0 remote-sync:diff-file (span.name.icon.icon-file-text)
     -7:27.4.0 core:paste (input.hidden-input)
     -7:12.2.0 remote-sync:diff-file (span.name.icon.icon-file-text)
     -6:50.9.0 remote-sync:diff-folder (span.name.icon.icon-file-directory)
     -5:57.8.0 git-diff:toggle-diff-list (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
  5x -5:47.7.0 symbols-view:toggle-file-symbols (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
  2x -5:31.3.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
     -3:39.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:14.1.0 core:backspace (input.hidden-input)
     -3:13.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
busy-signal 1.4.1 
emmet 2.4.3 
intentions 1.1.2 
language-svg 0.9.2 
language-vue 0.21.2 
linter 2.1.4 
linter-eslint 8.1.7 
linter-ui-default 1.2.4 
remote-sync 4.1.5 
svg-preview 0.11.0 
```

**Comment by willgdjones** [comment] 2017-05-19 10:22
Same issue here - remote sync was working just fine, until yesterday when it stopped working and threw this error.

**Comment by dschwen** [comment] 2017-05-22 23:37
c328bee should fix this bug. `traverseTree` needs a fourth argument (this is not optional anymore)!

I'm having a little trouble getting this package to work though. I set up the sync and managed it to upload an individual file, but the context menu item for uploading folders does not get registered on mac (and running upload folder from the command palette does nothing).

Anyhow, I'd appreciate if someone could test this patch or give me a hint what I might be missing here.

**Comment by AdsonCicilioti** [comment] 2017-07-21 16:36
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**:  Windows 10 PRO version
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5


### Stack Trace

Uncaught TypeError: q.drain is not a function

```
At B:\Users\Adson\.atom\packages\remote-sync\node_modules\fs-plus\node_modules\async\lib\async.js:909

TypeError: q.drain is not a function
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:909:23
    at /packages/remote-sync/node_modules/fs-plus/node_modules/async/lib/async.js:44:16
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:438:24
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -4:18.4.0 remote-sync:upload-file (span.name.icon.php-icon.dark-blue)
     -1:56.5.0 remote-sync:upload-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
atom-material-numix-syntax 0.2.1 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.4 
busy-signal 1.4.3 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.9 
intentions 1.1.2 
intentions-colorpicker 1.0.1 
json-converter 0.2.4 
language-csv 1.1.2 
linter 2.2.0 
linter-jshint 3.1.5 
linter-ui-default 1.6.3 
logo-file-icons 1.11.0 
material-monokai-syntax 1.0.1 
material-ui 1.0.10 
minimap 4.29.0 
one-dark-material-syntax 1.0.3 
pigments 0.39.1 
remote-sync 4.1.5 
tablr 1.8.3 
tabular 0.1.0 
```

**Comment by dschwen** [comment] 2017-07-21 17:03
This is identical to issue #402, and there is already pull request #374
that fixes this. But it had been waiting to get merged. Looks like the
maintainers of this project are on an extended summer vacation.

**Comment by nedtobin** [comment] 2017-10-19 23:29
I've noticed this happens usually when I'm trying to sync a new folder that doesn't exist yet on the upload server, if that helps any.

**Closed** 2017-10-24 17:44 UTC
