### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Documents/Tenrec/Tenrec_Client_Portal/...

### ISSUE THREAD

**Issue by hiitsdustindavis** [yongkangchen/remote-sync#367] opened 2017-02-09 20:02 UTC
[Enter steps to reproduce:]

Not sure of the steps to reproduce the error. My directory path is good. I copied it directly from commandline. 
The directory path is being duplicated and passed as a single string.

**Atom**: 1.14.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/dustin_tenrec/Documents/Tenrec/Tenrec_Client_Portal/Dev/wp-content/Users/dustin_tenrec/Documents/Tenrec/Tenrec_Client_Portal/Dev/wp-content/themes/twentysixteen-child/style.css'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/Users/dustin_tenrec/Documents/Tenrec/Tenrec_Client_Portal/Dev/wp-content/Users/dustin_tenrec/Documents/Tenrec/Tenrec_Client_Portal/Dev/wp-content/themes/twentysixteen-child/style.css'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at RemoteSync.isDirectory (/packages/remote-sync/lib/RemoteSync.coffee:200:23)
    at RemoteSync.monitorFile (/packages/remote-sync/lib/RemoteSync.coffee:134:42)
    at /packages/remote-sync/lib/RemoteSync.coffee:225:13
```

### Commands

```
     -7:56.9.0 remote-sync:configure (span.name.icon.icon-file-directory)
  4x -6:52.7.0 core:backspace (input.hidden-input)
     -5:45.6.0 remote-sync:configure (span.name.icon.icon-file-directory)
     -1:10.3.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.2.4 
linter 1.11.21 
pigments 0.38.0 
remote-sync 4.1.5 
```

**Comment by daverickdunn** [comment] 2017-11-05 16:16
Duplicate of issue: #273

**Closed by daverickdunn** 2017-11-05 16:16 UTC
