### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by bgencacat** [yongkangchen/remote-sync#319] opened 2016-09-24 12:27 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.0-beta5
**Electron Version**: 0.37.8
**System**: Linux Mint
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.1.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /home/bgencacat/.atom/packages/remote-sync/node_modules/graceful-fs/polyfills.js:18

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/home/bgencacat/.atom/packages/remote-sync/node_modules/graceful-fs/polyfills.js:18:9)
    at lint (/home/bgencacat/.atom/packages/jshint/index.js:229:10)
    at complete (/home/bgencacat/.atom/packages/jshint/node_modules/lodash/index.js:7697:25)
    at delayed (/home/bgencacat/.atom/packages/jshint/node_modules/lodash/index.js:7707:11)
```
### Commands

```
     -6:03.7.0 core:paste (atom-text-editor.editor.is-focused)
  2x -6:03.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -6:02.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:01.5.0 core:save (atom-text-editor.editor.is-focused)
     -5:55 core:copy (atom-text-editor.editor.is-focused)
     -5:52.8.0 core:paste (atom-text-editor.editor.is-focused)
     -5:52 core:save (atom-text-editor.editor.is-focused)
  3x -5:36.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:33.8.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -5:27.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:26.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -5:12.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:11.5.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -5:11.3.0 core:save (atom-text-editor.editor.is-focused)
  5x -5:03.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:01.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "activate-power-mode"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "github-atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.9.0 (inactive)
angularjs, v0.3.5 (active)
atom-alignment, v0.12.1 (active)
autocomplete-modules, v1.6.3 (active)
autocomplete-php, v0.3.7 (active)
autocomplete-plus, v2.31.3 (active)
autocomplete-python, v1.8.6 (active)
color-picker, v2.2.2 (active)
docblockr, v0.8.5 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.19 (active)
github-atom-light-syntax, v0.2.0 (active)
jQuery, v1.2.4 (active)
jquery-snippets, v11.0.0 (active)
jshint, v1.8.6 (active)
language-apache, v1.6.0 (active)
language-htaccess, v0.1.1 (active)
language-ini, v1.16.0 (active)
language-nginx, v0.6.2 (active)
linter, v1.11.16 (active)
linter-jshint, v2.1.0 (active)
linter-jsonlint, v1.3.0 (active)
linter-php, v1.2.0 (active)
nodejs-snippets, v2.0.2 (active)
pretty-json, v1.6.0 (active)
python-indent, v1.0.0 (active)
remote-sync, v4.1.2 (active)
Stylus, v3.0.0 (active)
wordpress-api, v1.2.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.3 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by daverickdunn** [comment] 2017-11-05 16:16
Duplicate of issue: #273

**Closed by daverickdunn** 2017-11-05 16:16 UTC
Labels: bug, Needs checking
