### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Documents/webside/test_taironlife/css/...

### ISSUE THREAD

**Issue by eboy3575** [yongkangchen/remote-sync#414] opened 2017-06-13 13:11 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/mis/Documents/webside/test_taironlife/css/styles.css'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/Users/mis/Documents/webside/test_taironlife/css/styles.css'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at RemoteSync.isDirectory (/packages/remote-sync/lib/RemoteSync.coffee:200:23)
    at RemoteSync.monitorFile (/packages/remote-sync/lib/RemoteSync.coffee:134:42)
    at /packages/remote-sync/lib/RemoteSync.coffee:225:13
```

### Commands

```
  4x -4:16.6.0 core:close (input.hidden-input)
     -4:15.1.0 application:open (atom-pane.pane.active)
     -2:10 settings-view:open (a.btn-issue.btn.btn-error)
  3x -1:41.5.0 core:backspace (input.hidden-input)
     -1:40.3.0 core:confirm (input.hidden-input)
     -0:47.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-bootstrap3 1.2.12 
cht-menu 0.3.1 
remote-sync 4.1.5 
```

**Comment by daverickdunn** [comment] 2017-11-05 16:17
Duplicate of issue: #273

**Closed by daverickdunn** 2017-11-05 16:17 UTC
