### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport

### ISSUE THREAD

**Issue by DFelten** [yongkangchen/remote-sync#366] opened 2017-02-02 12:30 UTC
[Enter steps to reproduce:]

1. Try to upload a folder

**Atom**: 1.14.0-beta3 x64
**Electron**: 1.3.13
**OS**: DESKTOP-OLJ5L9G
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in C:\Users\Daniel\Git\Portal\MediaWiki\mw_bot\.remote-sync.json

```
At C:\Users\Daniel\.atom\packages\remote-sync\lib\RemoteSync.coffee:256

Error: [remote-sync] invalid transport: undefined in C:\Users\Daniel\Git\Portal\MediaWiki\mw_bot\.remote-sync.json
    at RemoteSync.createTransport (/packages/remote-sync/lib/RemoteSync.coffee:256:17)
    at RemoteSync.getTransport (/packages/remote-sync/lib/RemoteSync.coffee:262:19)
    at RemoteSync.uploadFile (/packages/remote-sync/lib/RemoteSync.coffee:108:37)
    at /packages/remote-sync/node_modules/fs-plus/lib/fs-plus.js:437:17
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:27 remote-sync:upload-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.17 
atom-clock 0.1.3 
atom-material-syntax 1.0.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
atom-react-native-autocomplete 0.0.27 
atom-react-native-css 1.1.3 
atom-terminal 0.8.0 
atom-terminal-panel 4.4.4 
autocomplete-bibtex 0.7.0 
docblockr 0.9.1 
file-icons 2.0.13 
git-plus 7.2.0 
highlight-selected 0.12.0 
intentions 1.1.2 
language-babel 2.52.0 
language-javascript-jsx 0.3.7 
language-latex 1.0.0 
latex 0.42.3 
latex-autocomplete 1.0.0 
latexer 0.3.0 
linter 1.11.21 
linter-chktex 1.3.0 
linter-spell 0.12.6 
linter-spell-latex 0.9.1 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
minimap-split-diff 0.3.2 
monokai 0.20.0 
open-this 0.4.0 
pdf-view 0.54.0 
plain-simple 1.0.3 
project-manager 3.3.3 
react-native-snippets 0.3.0 
remote-sync 4.1.5 
split-diff 1.1.1 
sync-settings 0.8.1 
todo-show 1.9.0 
wordcount 2.10.3 
Zen 0.16.4 
```

**Comment by DFelten** [comment] 2017-02-02 12:45
Ok, it was an syntax error in the .remote-sync.json. In the list of ignored files, a comma was too much in the end.

**Comment by enoversum** [comment] 2017-05-02 15:41
@DFelten That was no problem a short while ago. The latest Beta version seems to have broken it. But thank you for the tip, that finally helped!

**Comment by daverickdunn** [comment] 2017-10-26 14:06
Duplicate of #285

**Closed by daverickdunn** 2017-10-26 14:06 UTC
