### ISSUE TITLE
uploadMirrors not working

### ISSUE THREAD

**Issue by campusman** [yongkangchen/remote-sync#324] opened 2016-09-30 03:59 UTC
A colleague and I both upgraded remote-sync to 4.1.4 as prompted by Atom today and now neither of us appear to be able to upload files we save to the single uploadmirror server we have set in our remote-sync.json files.

-She is on Mac OSX 10.12
-I am on Windows 10.
-Both of us are using Atom 1.10.2
-Both of us are using remote-sync 4.1.4 which we upgraded to today. (9/29/16)
-We have no changed our remote-sync.json file with our main server and the extra upload mirror server in the last year at least and it seemed to be working fine until now. 
-manual file download from primary server in config json works normally still via remote-sync context menu. 
-uploadOnSave works correctly for the primary server in the remote-sync.json, only the uploadmirror server is having a problem and not uploading as indicated in the upload log window.
-I have totally uninstalled/reinstalled remote-sync.
-I removed my existing remote-sync.json and used the GUI config window on the folder to generate a new one and then manually added in the uploadMirrors to the config.
-All credentials have been verified to be active on both servers manually via FileZilla.
-Swapping the primary/secondary server hostname/credentials in the remote-sync.json results in the main server in the config file still uploading, but the previously-main-now-uploadmirror server does not upload.

Below is an anonymized version of our config file, only the hostname, username, and passwords have been changed. Everything else is as was generated or as I have now.

```
{
    "transport": "ftp",
    "uploadOnSave": true,
    "useAtomicWrites": false,
    "deleteLocal": false,
    "hostname": "1.1.1.1",
    "port": "21",
    "target": "/",
    "ignore": [
        ".remote-sync.json",
        ".git/**"
    ],
    "username": "user",
    "password": "******",
    "watch": [],
    "uploadMirrors": [{
        "transport": "ftp",
        "hostname": "2.2.2.2",
        "port": "21",
        "target": "/",
        "username": "user",
        "password": "******"
    }]
}
```

Any input you have on why this might not be working anymore would be appreciated.

**Comment by DarekDeo** [comment] 2016-09-30 13:22
Same here, upload is not working. Client first connects to ftp with success then upload takes forever.

**Comment by Bearness** [comment] 2016-10-11 14:33
I need to get this uploadMirrors to work, but it only uploads to last uploadMirrors array
`{
  "transport": "ftp",
  "uploadOnSave": true,
  "useAtomicWrites": false,
  "deleteLocal": false,
  "hostname": "host",
  "target": "/",
  "username": "username",
  "password": "*******",
  "ignore": [
    ".remote-sync.json",
    ".git/**"
  ],
  "uploadMirrors": [
    {
      "transport": "ftp",
      "port": 21,
      "uploadOnSave": true,
      "useAtomicWrites": false,
      "deleteLocal": false,
      "hostname": "host",
      "target": "/dir1",
      "username": "username2",
      "password": "*******"
    },
   {
      "transport": "ftp",
      "port": 21,
      "uploadOnSave": true,
      "useAtomicWrites": false,
      "deleteLocal": false,
      "hostname": "host",
      "target": "/dir2",
      "username": "username2",
      "password": "*******"
    }
  ]
}`

**Comment by laymance** [comment] 2016-10-19 11:50
**There is an issue and mirrors are definitely broken.**  I have tracked it to lines 22-23 in lib/UploadListener.coffee (see lines 19-24 below):

```
    if @queue.length()
      task = @queue._tasks.head
      while task
       if task.data.localFilePath == localFilePath && task.data.action == action
         task.data.discard = true
       task = task.next
```

It relates to the new single queue that was added recently for all actions (uploads and deletes previously had their own queues).  It loops through the queue to remove duplicate entries so that it isn't performing the same action multiple times. 

It checks the localFilePath and the action (upload or delete) and if they match, it discards all but one.  The problem is that it doesn't take the hostname and target path into consideration, so when you look at just the local file path and action, when using mirrors, there will definitely be duplicates.

I'll have to play around with it to try to find a fix.  CoffeeScript isn't one of my normal languages that I work in, so I'm figuring it out as I go.  If I come up with a fix I'll make a pull request for it, otherwise, maybe someone else can knock it out easily.

**Comment by laymance** [comment] 2016-10-19 12:24
Made a fix and tested, have issued a pull request for it.  (Pull request #330)

**Comment by elistone** [comment] 2016-10-19 14:03
Merged pull request and pushed version thanks @laymance for the fix.

**Closed by elistone** 2016-10-19 14:03 UTC
Labels: Needs checking

**Comment by campusman** [comment] 2016-10-19 19:23
Confirmed that upload mirrors are working again. Good job, thanks all for the fix!
