### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/GitHub/nabu-3/composer-installer-plug...

### ISSUE THREAD

**Issue by nabu-3** [yongkangchen/remote-sync#371] opened 2017-02-23 16:54 UTC
[Enter steps to reproduce:]

1. ... Remove .remote.sync.json from the console.
2. ... Try to upload a file.

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/rgutierrez/GitHub/nabu-3/composer-installer-plugin/.remote-sync.json'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

Error: ENOENT: no such file or directory, lstat '/Users/rgutierrez/GitHub/nabu-3/composer-installer-plugin/.remote-sync.json'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Object.realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at /packages/remote-sync/index.coffee:126:44
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:27)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:891:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  3x -7:25.3.0 editor:select-to-beginning-of-word (input.hidden-input)
     -7:24.6.0 editor:select-to-end-of-word (input.hidden-input)
     -7:23.8.0 core:backspace (input.hidden-input)
  2x -7:22 core:move-down (input.hidden-input)
     -4:00.3.0 core:save (input.hidden-input)
     -3:57 core:backspace (input.hidden-input)
  2x -3:55.6.0 core:save (input.hidden-input)
     -3:40 remote-sync:configure (span.name.icon.icon-repo)
     -2:51.2.0 core:backspace (input.hidden-input)
 10x -2:49.2.0 core:move-down (input.hidden-input)
  2x -2:36.6.0 core:save (input.hidden-input)
     -0:48.8.0 git-plus:menu (input.hidden-input)
  2x -0:44.9.0 core:move-down (input.hidden-input)
     -0:44 core:confirm (input.hidden-input)
  3x -0:39.4.0 core:backspace (input.hidden-input)
  2x -0:17.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-html-preview 0.1.22 
context-git 0.15.0 
data-atom 0.24.1 
git-clone 0.2.0 
git-plus 7.3.0 
gitkraken 0.4.2 
hex 0.6.2 
hyperclick undefined 
intentions 1.1.2 
language-apache 1.7.0 
language-asp 1.0.0 
language-asp-html 0.2.0 
language-diff 0.7.0 
language-smarty 1.7.0 
lint 0.0.1 
linter 1.11.23 
linter-bootlint 1.0.4 
linter-csslint 1.3.3 
linter-json-lint 0.1.1 
linter-php 1.3.1 
linter-phpmd 1.5.3 
linter-sass-lint 1.7.4 
linter-scss-lint 3.1.0 
linter-tidy 2.3.0 
lipsum 0.1.0 
minimap 4.26.8 
minimap-git-diff 4.3.1 
php-integrator-annotations 1.1.1 
php-integrator-autocomplete-plus 1.2.0 
php-integrator-base 2.1.10 
php-integrator-call-tips 1.2.1 
php-integrator-linter 1.3.0 
php-integrator-navigation 1.1.2 
php-integrator-refactoring 1.3.1 
php-integrator-symbol-viewer 0.6.4 
php-integrator-tooltips 1.1.5 
project-manager 3.3.3 
remote-sync 4.1.5 
split-diff 1.1.4 
todo-show 1.11.0 
```

**Comment by daverickdunn** [comment] 2017-11-05 16:17
Duplicate of issue: #273

**Closed by daverickdunn** 2017-11-05 16:17 UTC
