### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined in ~/htdocs/splinter/.remote-sync.json

### ISSUE THREAD

**Issue by marcelobns** [yongkangchen/remote-sync#380] opened 2017-04-03 20:44 UTC
Error: Permission denied(Sudo privileges needed).

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in /Users/marcelobarbosa/htdocs/splinter/.remote-sync.json

```
At /Users/marcelobarbosa/.atom/packages/remote-sync/lib/RemoteSync.coffee:256

Error: [remote-sync] invalid transport: undefined in /Users/marcelobarbosa/htdocs/splinter/.remote-sync.json
    at RemoteSync.createTransport (/packages/remote-sync/lib/RemoteSync.coffee:256:17)
    at RemoteSync.getTransport (/packages/remote-sync/lib/RemoteSync.coffee:262:19)
    at RemoteSync.uploadFile (/packages/remote-sync/lib/RemoteSync.coffee:108:37)
    at handleEvent (/packages/remote-sync/index.coffee:46:14)
    at /packages/remote-sync/index.coffee:100:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:21.1.0 editor:newline (input.hidden-input)
     -0:20.4.0 core:paste (input.hidden-input)
     -0:18.4.0 core:move-up (input.hidden-input)
     -0:18 core:move-right (input.hidden-input)
     -0:16.7.0 core:save (input.hidden-input)
     -0:09.7.0 remote-sync:upload-file (div.line)
```

### Non-Core Packages

```
api-docs 0.0.6 
chrome-dark-syntax 0.5.0 
dracula-theme 2.0.0 
file-icons 2.1.2 
imdone-atom 2.1.25 
language-blade 0.29.0 
platformio-ide-terminal 2.5.0 
remote-sync 4.1.5 
```

**Comment by daverickdunn** [comment] 2017-10-26 14:06
Duplicate of #285

**Closed by daverickdunn** 2017-10-26 14:06 UTC
