### ISSUE TITLE
"Remote Sync" not appearing after right click.

### ISSUE THREAD

**Issue by andrewtoups** [yongkangchen/remote-sync#440] opened 2017-09-20 16:44 UTC
When I select my project folder, "Remote Sync" is not appearing in the context menu.

Using 1.20.1 on Mavericks.

**Comment by aidanranney** [comment] 2017-09-21 00:22
I am also having this same issue.
Atom v. 1.20.1 on El Capitan

Hi toups! #SB

**Comment by eastonYi** [comment] 2017-09-25 00:58
use the commend with keybinding `ctrl+shift+p` and input `remote`

**Comment by DimitryDushkin** [comment] 2017-10-03 13:29
No "remote" thing in ctrl+shift+p menu.

**Comment by DimitryDushkin** [comment] 2017-10-03 13:31
I had incomplete packages issue (look at bug icon at bottom left). Rebuilding packages helped.

**Comment by daverickdunn** [comment] 2017-10-04 07:54
For a hot-fix see issue: https://github.com/yongkangchen/remote-sync/issues/433

Remote-sync _is working_, it's just not appearing in the project menu...

**Comment by daverickdunn** [comment] 2017-10-13 12:59
Duplicate of https://github.com/yongkangchen/remote-sync/issues/433

Will patch in the coming days.

**Closed by daverickdunn** 2017-10-13 12:59 UTC
