### ISSUE TITLE
Not working on atom 1.20.1

### ISSUE THREAD

**Issue by Timme777** [yongkangchen/remote-sync#441] opened 2017-09-28 10:48 UTC
For some reason the remote-sync package is not working anymore? Could it be after an automatic update of atom core?

**Comment by daverickdunn** [comment] 2017-10-04 07:42
See issue for a hot-fix: https://github.com/yongkangchen/remote-sync/issues/433

I've provided a pull request, but this appears to be abandonware... :/

**Comment by daverickdunn** [comment] 2017-10-13 12:56
Duplicate of https://github.com/yongkangchen/remote-sync/issues/433

Will patch in the coming days.

**Closed by daverickdunn** 2017-10-13 12:56 UTC
