### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined

### ISSUE THREAD

**Issue by AdsonCicilioti** [yongkangchen/remote-sync#430] opened 2017-08-02 21:02 UTC
[Enter steps to reproduce:]

1. ... Right click > Remote Sync > Upload

### My code in .remote-sync.json file:

```
{
  "transport": "scp",
  "uploadOnSave": false,
  "useAtomicWrites": false,
  "deleteLocal": false,
  "hostname": "ec2-xxx-xxx-xxx-xxx.compute-1.amazonaws.com",
  "port": "22",
  "target": "/var/www/frutasbrasil/wp-content/themes/odin/",
  "ignore": [
    ".remote-sync.json",
    ".git/**",
    "**.DS_Store",
    "**Thumbs.db",
    "*.md",
    ".vscode"
    "gulpfile.js",
    "yarn.lock",
    ".vscode",
    "package.json",
    ".gitignore",
    ".bowerrc",
    ".bower.json",
    "src",
    "src/**",
    "*.zip",
    "*.tar.gz",
    "*.sublime-project",
    "*.sublime-workspace",
    "node_modules",
    "node_modules/**",
    ".ftppass"
  ],
  "username": "ubuntu",
  "keyfile": "B:\\Users\\Adson\\Web\\AWS\\keypair\\vallefrutas-aws.pem",
  "watch": [
    "/assets/"
  ]
}

```

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Windows 10 PRO
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in U:\frutasbrasilsul.com.br\wp-content\themes\odin\.remote-sync.json

```
At B:\Users\Adson\.atom\packages\remote-sync\lib\RemoteSync.coffee:256

Error: [remote-sync] invalid transport: undefined in U:\frutasbrasilsul.com.br\wp-content\themes\odin\.remote-sync.json
    at RemoteSync.createTransport (/packages/remote-sync/lib/RemoteSync.coffee:256:17)
    at RemoteSync.getTransport (/packages/remote-sync/lib/RemoteSync.coffee:262:19)
    at RemoteSync.uploadFile (/packages/remote-sync/lib/RemoteSync.coffee:108:37)
    at handleEvent (/packages/remote-sync/index.coffee:46:14)
    at /packages/remote-sync/index.coffee:100:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1320:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:30.4.0 remote-sync:upload-file (div.line)
```

### Non-Core Packages

```
remote-sync 4.1.5 
```

**Comment by daverickdunn** [comment] 2017-10-24 07:47
Error is caused by missing comma at: `".vscode"`.

This error message is obviously deceiving, will be improving this by verifying JSON.

**Comment by daverickdunn** [comment] 2017-10-26 14:07
Duplicate of #285

**Closed by daverickdunn** 2017-10-26 14:07 UTC
Labels: enhancement
