### ISSUE TITLE
Uncaught Error: [remote-sync] invalid transport: undefined in C:/_DEV\_WORK\_BystricaCity\.remote...

### ISSUE THREAD

**Issue by azurinko** [yongkangchen/remote-sync#422] opened 2017-06-27 10:38 UTC
[Enter steps to reproduce:]

1. ... I have this file ...
```
{
  "transport": "sftp",
  "hostname": "******",
  "port": 22,
  "username": "******",
  "password": "******",
  "target": "/var/www/clients/client0/web240/web/",
  "ignore": [
    ".remote-sync.json",
    ".git/**"
    "/ff/"
  ],
  "watch":[
    "/"
  ]
}
```
Which Worked yesterday, today it's throwing an error.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: [remote-sync] invalid transport: undefined in C:\_DEV\_WORK\_BystricaCity\.remote-sync.json

```
At C:\Users\yamami\.atom\packages\remote-sync\lib\RemoteSync.coffee:256

Error: [remote-sync] invalid transport: undefined in C:\_DEV\_WORK\_BystricaCity\.remote-sync.json
  at RemoteSync.createTransport (/packages/remote-sync/lib/RemoteSync.coffee:256:17)
  at RemoteSync.getTransport (/packages/remote-sync/lib/RemoteSync.coffee:262:19)
  at RemoteSync.uploadFile (/packages/remote-sync/lib/RemoteSync.coffee:108:37)
  at handleEvent (/packages/remote-sync/index.coffee:46:14)
  at /packages/remote-sync/index.coffee:100:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (<embedded>:18904:35)
  at CommandRegistry.handleCommandEvent (<embedded>:18642:65)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (<embedded>:18805:25)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (<embedded>:1554:34)
  at EventEmitter.outerCallback (<embedded>:2012:31)
  at emitThree (events.js:116:13)
  at EventEmitter.emit (events.js:194:7)

```

### Commands

```
  7x -5:11.8.0 intentions:highlight (input.hidden-input)
     -5:11.4.0 core:save (input.hidden-input)
     -3:11.2.0 core:backspace (input.hidden-input)
     -3:10.4.0 core:confirm (input.hidden-input)
     -2:02.7.0 remote-sync:upload-file (div.line)
     -1:54.2.0 intentions:highlight (input.hidden-input)
     -1:54 core:save (input.hidden-input)
     -1:47.3.0 remote-sync:upload-file (span.syntax--comment.syntax--line.syntax--double-slash.syntax--php)
     -1:39.4.0 core:backspace (input.hidden-input)
     -1:38.2.0 intentions:highlight (input.hidden-input)
     -1:37.9.0 core:save (input.hidden-input)
     -1:34 remote-sync:upload-file (span.syntax--comment.syntax--line.syntax--double-slash.syntax--php)
     -1:25.4.0 core:backspace (input.hidden-input)
     -1:24.6.0 intentions:highlight (input.hidden-input)
     -1:24.4.0 core:save (input.hidden-input)
     -1:21.8.0 remote-sync:upload-file (span.syntax--source.syntax--php)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
docblockr 0.10.5 
emmet 2.4.3 
intentions 1.1.2 
language-vue-component 0.5.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-flow-plus 3.1.0 
linter-ui-default 1.6.2 
nuclide 0.232.0 
open-recent 5.0.0 
pigments 0.39.1 
remote-sync 4.1.5 
todo-show 1.11.0 
tool-bar 1.1.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by AdsonCicilioti** [comment] 2017-08-02 22:25
same problem.

**Comment by daverickdunn** [comment] 2017-10-26 14:07
Duplicate of #285

**Closed by daverickdunn** 2017-10-26 14:07 UTC
