### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Michael/Documents/Repositories/c...

### ISSUE THREAD

**Issue by MichaelGuarin0** [yongkangchen/remote-sync#387] opened 2017-04-27 15:32 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/Michael/Documents/Repositories/cmpt422/.remote-sync.json'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

Error: ENOENT: no such file or directory, lstat '/Users/Michael/Documents/Repositories/cmpt422/.remote-sync.json'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Object.realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at /packages/remote-sync/index.coffee:126:44
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1092:27)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1058:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:920:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.saveActivePaneItem (/app.asar/src/workspace.js:851:33)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  6x -4:22.6.0 core:save (input.hidden-input)
     -3:11.8.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -3:10.3.0 core:select-all (input.hidden-input)
     -3:08.5.0 core:copy (input.hidden-input)
     -2:59.2.0 tree-view:remove (span.name.icon.database-icon.medium-yellow)
     -2:53.6.0 core:select-all (input.hidden-input)
     -2:52.6.0 core:move-left (input.hidden-input)
     -2:51.3.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
     -2:50.5.0 core:select-all (input.hidden-input)
     -2:50.2.0 core:backspace (input.hidden-input)
     -2:50 core:paste (input.hidden-input)
     -2:48.4.0 core:save (input.hidden-input)
     -1:50 tree-view:remove (span.name.icon.database-icon.medium-yellow)
     -1:25.9.0 remote-sync:upload-git-change (span.name.icon.icon-file-directory)
     -1:08.5.0 remote-sync:configure (span.name.icon.icon-file-directory)
     -0:40.8.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-beautify 0.29.23 
atom-clock 0.1.7 
atom-keyboard-macros 0.9.2 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.9 
autoclose-html 0.23.0 
autocomplete-haskell 0.7.2 
autocomplete-java 1.2.5 
autocomplete-python 1.8.63 
autocomplete-R 0.6.0 
close-tags 0.6.0 
color-picker 2.2.5 
d3-snippets 1.0.0 
file-icons 2.1.3 
git-plus 7.6.0 
haskell-ghc-mod 1.19.9 
highlight-selected 0.13.1 
Hydrogen 1.11.2 
ide-haskell 1.9.6 
ide-haskell-repl 0.6.0 
keyboard-scroll 0.7.0 
kite 0.21.2 
language-haskell 1.12.1 
language-hql 4.1.0 
linter-python-pep8 0.2.0 
minimap 4.27.1 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
open-in-browsers 0.0.19 
package-list 0.1.2 
pdf-view 0.57.0 
pretty-json 1.6.3 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
qolor 0.4.1 
remote-sync 4.1.5 
symbols-tree-view 0.14.0 
todo-show 1.11.0 
vim-mode-plus 0.91.0 
```

**Comment by enoversum** [comment] 2017-05-02 15:31
@MichaelGuarin0 It seems this error occurs with the recent versions of Atom, as you can see from the various same bug messages here on GitHub. Unfortunately, @yongkangchen seems to have other projects on his/her desk. No response to any of our problems since quite a while, so I hope we'll get back the functionality soon :).

**Comment by krzysmierz** [comment] 2017-05-12 09:04
especially at 1.17

**Comment by daverickdunn** [comment] 2017-11-05 16:17
Duplicate of issue: #273

**Closed by daverickdunn** 2017-11-05 16:17 UTC
