### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory lstat

### ISSUE THREAD

**Issue by gau1991** [yongkangchen/remote-sync#294] opened 2016-06-22 08:57 UTC
After deleting .remote-sync.json file got the error

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package, v4.1.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/gaurav/github/code/perforce-client/.remote-sync.json'

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

Error: ENOENT: no such file or directory, lstat '/home/gaurav/github/code/perforce-client/.remote-sync.json'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at Object.realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:304:29)
    at /home/gaurav/.atom/packages/remote-sync/index.coffee:121:44
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -7:52.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -7:50.3.0 core:backspace (atom-text-editor.editor.is-focused)
  7x -7:45.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
 35x -7:34.4.0 core:move-down (atom-text-editor.editor.is-focused)
 13x -7:32.6.0 core:move-up (atom-text-editor.editor.is-focused)
  8x -6:53.6.0 core:move-down (atom-text-editor.editor.is-focused)
 19x -6:51.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:50.6.0 core:move-down (atom-text-editor.editor.is-focused)
 27x -6:50.2.0 core:move-left (atom-text-editor.editor.is-focused)
  8x -6:47.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -6:42.9.0 core:save (atom-text-editor.editor.is-focused)
     -6:38.5.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -6:38.1.0 core:save (atom-text-editor.editor.is-focused)
 30x -6:36.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:24.8.0 tree-view:remove (span.name.icon.icon-file-text)
  3x -0:07.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.8
file-icons, v1.7.15
language-chef, v0.9.0
minimap, v4.24.6
remote-sync, v4.1.2

# Dev
No dev packages
```

**Comment by daverickdunn** [comment] 2017-11-05 16:16
Duplicate of issue: #273

**Closed by daverickdunn** 2017-11-05 16:16 UTC
Labels: bug
