### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '~/Documents/src/deepXlsmig/css/styles.css'

### ISSUE THREAD

**Issue by deepseis01** [yongkangchen/remote-sync#424] opened 2017-07-05 22:02 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 14.04.5
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/home/lxiang/Documents/src/deepXlsmig/css/styles.css'

```
At fs.js:992

Error: ENOENT: no such file or directory, stat '/home/lxiang/Documents/src/deepXlsmig/css/styles.css'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:275:16)
    at RemoteSync.isDirectory (/packages/remote-sync/lib/RemoteSync.coffee:200:23)
    at RemoteSync.monitorFile (/packages/remote-sync/lib/RemoteSync.coffee:134:42)
    at /packages/remote-sync/lib/RemoteSync.coffee:225:13
```

### Commands

```
     -1:57.9.0 snippets:next-tab-stop (input.hidden-input)
     -1:57.9.0 snippets:expand (input.hidden-input)
     -1:57.9.0 editor:indent (input.hidden-input)
     -1:57.1.0 core:backspace (input.hidden-input)
     -1:56.8.0 core:move-down (input.hidden-input)
     -1:56.2.0 core:move-up (input.hidden-input)
     -1:55.9.0 core:backspace (input.hidden-input)
     -1:55.6.0 core:move-down (input.hidden-input)
  4x -1:55.3.0 core:move-right (input.hidden-input)
  7x -1:54.4.0 core:backspace (input.hidden-input)
     -1:35 core:move-down (input.hidden-input)
 32x -1:34.6.0 core:move-right (input.hidden-input)
 11x -1:19.3.0 core:move-left (input.hidden-input)
     -1:17.5.0 core:move-right (input.hidden-input)
 22x -1:17.2.0 core:backspace (input.hidden-input)
     -0:44.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
git-plus 7.9.3 
language-fortran 2.1.0 
remote-sync 4.1.5 
```

**Comment by daverickdunn** [comment] 2017-11-05 16:17
Duplicate of issue: #273

**Closed by daverickdunn** 2017-11-05 16:17 UTC
