### ISSUE TITLE
After Atom upgrade to 1.21.0 Remote sync menu options not working

### ISSUE THREAD

**Issue by Om1986** [yongkangchen/remote-sync#443] opened 2017-10-05 00:03 UTC
Today after upgrade to atom version 1.21.0, remote-sync stopped working. Right click is showing menu options but click on the options like Configure, Upload folder not working.
I had enable auto-save in my remote-sync.json and that is also not working. Can somebody please post a hot fix for this ?

**Comment by chrisduong** [comment] 2017-10-06 08:44
me too

**Comment by daverickdunn** [comment] 2017-10-13 12:54
Duplicate of https://github.com/yongkangchen/remote-sync/issues/433

Hotfix provided in that link.

Will patch in the coming days.

**Closed** 2017-10-13 12:54 UTC
