### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Applications/XAMPP/xamppfiles/htdocs/i...

### ISSUE THREAD

**Issue by oLuciaZo** [yongkangchen/remote-sync#368] opened 2017-02-13 08:10 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [remote-sync](https://github.com/yongkangchen/remote-sync) package 4.1.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Applications/XAMPP/xamppfiles/htdocs/iot/.remote-sync.json'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

Error: ENOENT: no such file or directory, lstat '/Applications/XAMPP/xamppfiles/htdocs/iot/.remote-sync.json'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Object.realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at /packages/remote-sync/index.coffee:126:44
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:27)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:890:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -9:03.0 core:copy (input.hidden-input)
     -8:57.4.0 core:paste (input.hidden-input)
     -8:56.1.0 core:save (input.hidden-input)
  6x -8:25.2.0 core:backspace (input.hidden-input)
     -8:19.7.0 core:save (input.hidden-input)
     -6:55.9.0 core:paste (input.hidden-input)
     -6:48.3.0 core:copy (input.hidden-input)
     -0:11.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
remote-sync 4.1.5 
```

**Comment by daverickdunn** [comment] 2017-11-05 16:17
Duplicate of issue: #273

**Closed by daverickdunn** 2017-11-05 16:17 UTC
